image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu

stages:
  - build
  - test
  - coverage
  - deploy

build-from-base:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:install-ubuntu-base
  stage: build
  only:
    - install
  script:
    - python3 make
    - echo $(barrnap -h)
    - echo $(prokka -h)
    - genomeAPCAT -h

build-from-base-user:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:install-ubuntu-base
  stage: build
  only:
    - install
  script:
    - python3 make --user
    - echo $(barrnap -h)
    - echo $(prokka -h)
    - ln -s $(pwd)/bin/genomeAPCAT /usr/local/bin
    - genomeAPCAT -h

build-from-barrnap:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:install-ubuntu-barrnapOnly
  stage: build
  only:
    - install
  script:
    - python3 make
    - echo $(barrnap -h)
    - echo $(prokka -h)
    - genomeAPCAT -h

build-from-prokka:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:install-ubuntu-prokkaOnly
  stage: build
  only:
    - install
  script:
    - python3 make
    - echo $(barrnap -h)
    - echo $(prokka -h)
    - genomeAPCAT -h

unit-test-ubuntu16.04:
  stage: test
  except:
    - docker
  before_script:
    - ./make
  script:
    - py.test test/test_unit
    - mv .coverage .coverage-unit
  artifacts:
    paths:
      - .coverage-unit
    expire_in: 1 hour

func-test-ubuntu16.04:
  stage: test
  except:
    - docker
  before_script:
    - ./make
  script:
    - py.test test/test_functional
    - mv .coverage .coverage-functional
  artifacts:
    paths:
      - .coverage-functional
    expire_in: 1 hour

coverage:
  stage: coverage
  except:
    - docker
  dependencies:
    - unit-test-ubuntu16.04
    - func-test-ubuntu16.04
  before_script:
    - pip3 install -r requirements.txt
  script:
    - coverage combine .coverage-unit .coverage-functional
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir -p public/htmlcov
    - mv htmlcov public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - master
