stages:
  - build
  - test
  - deploy

test-ubuntu16.04:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - pip3 install .
  script:
    - py.test test
  artifacts:
    paths:
      - pythoncode/htmlcov/
    expire_in: 2 min
    only: master

pages:
  stage: deploy
  dependencies:
    - test-ubuntu16.04
  script:
    - mv pythoncode/htmlcov public/
  artifacts:
    paths:
      - public
    expire_in: 2 min
  only:
    - master
