image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu

stages:
  - build
  - test
  - coverage
  - deploy

unit-test-ubuntu16.04:
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - pip3 install .
  script:
    - py.test test/test_unit
    - mv .coverage .coverage-unit
  artifacts:
    paths:
      - pythoncode/.coverage-unit
    expire_in: 1 hour

func-test-ubuntu16.04:
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - pip3 install .
  script:
    - py.test test/test_functional
    - mv .coverage .coverage-functional
  artifacts:
    paths:
      - pythoncode/.coverage-functional
    expire_in: 1 hour

coverage:
  stage: coverage
  except:
    - docker
  dependencies:
    - unit-test-ubuntu16.04
    - func-test-ubuntu16.04
  before_script:
    - cd pythoncode
    - pip3 install -r requirements.txt
  script:
    - coverage combine .coverage-unit .coverage-functional
    - coverage report
    - coverage html
  artifacts:
    paths:
      - pythoncode/htmlcov
    expire_in: 1 hour

pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mkdir public
    - mkdir public/htmlcov
    - mkdir public/others
    - cp pythoncode/index.html public/others
    - cp pythoncode/index.html public
    - mv pythoncode/htmlcov public
    - ls -la public
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - master
