stages:
  - build
  - test
  - deploy

test-ubuntu16.04:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - pip3 install .
  script:
    - ls -l
    - py.test test --cov pipelinepackage
  artifacts:
    paths:
      - htmlcov/

pages:
  stage: deploy
  dependencies:
    - test-ubuntu16.04
  script:
    - cd pythoncode
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
