variables:
    MYVAR: "plop"

test-ubuntu16.04:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - python3 setup.py install
  script:
    - python3 --version
