variables:
    MYVAR: "plop"

stages:
  - build
  - test
  - deploy

test-ubuntu16.04:
  image: registry-gitlab.pasteur.fr/aperrin/pipeline_annotation:testing-ubuntu
  stage: test
  except:
    - docker
  before_script:
    - cd pythoncode
    - pip3 install .
  script:
    - python3 --version
    - pip3 --version
    - pip --version
    - py.test
  artifacts:
    paths:
      - htmlcov/

pages:
  stage: deploy
  dependencies:
    - test-ubuntu16.04
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
